### ISSUE TITLE
H33 Links Repeated: links out to outdated & conflicting "title" attribute guidance

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/accessibility-ruleset-runner#19]
On the rulesets README, the custom rule for "Links Repeated" links out to:

https://www.w3.org/TR/WCAG20-TECHS/H33.html

I feel that the information presented on this page is not the best way to supplement link text, and could do more harm than good. Please can we remove it?

**Comment by scottizu** [comment]
Let's discuss the recommendation for Additional Context.  We may remove the rule altogether if these are no longer considered bugs.  We want to have 0 false positives.  As such, we would need to update the custom ruleset, modify the Test Library and remove the tests.  We would also bump the version for the custom ruleset, update documentation accordingly and release a new NPM package with the updated ruleset.

**Comment by ianmcburnie** [comment]
Yes, we can consider this issue blocked until context discussions are resolved (hopefully by next week) if you like. I was just thinking that in the interim we could remove that link, as it's potentially harmful, but I have no problem waiting.

**Comment by scottizu** [comment]
Looks like we are keeping this rule.  Re-open if that is not the case.

**Comment by ianmcburnie** [comment]
@scottizu I still don't think we should provide a link to a page that is advocating use of the `title` attribute on links. We have already identified that as an anti-pattern in MIND. I don’t think it’s a good situation to have two open source eBay projects giving conflicting advice.

Also applies to custom rule "Anchor Tag Title For New Windows".

Can we link out to H30 instead in both cases? H30 isn't perfect either, but at least it doesn't mention `title` attribute.
