### ISSUE TITLE
Integrate ESLint for all JavaScript source code

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/accessibility-ruleset-runner#20]
To ensure code quality and consistent formatting, we should integrate ESLint into the build/commit process:

https://eslint.org

Using our own config:

https://github.com/eBay/eslint-config-ebay

**Comment by scottizu** [comment]
Please submit a pull request to include this for commit.  Test steps are listed here: https://github.com/eBay/accessibility-ruleset-runner/blob/master/rulesets/tests/README.md

All contributors are required to run tests prior to commit.
